version: '3.9'
services:
  db:
    image: dev_postgresql
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  web:
    build: .
    user: $UID:$GID
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/[YOUR PROJECT]
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env


